# Le module NumPy.
## Un module qui permet de manipuler et d'effectuer des calculs beaucoup plus rapidement sur des gros tableaux.

In [334]:
import math
import numpy as np
# If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:
# To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
# >>> np.set_printoptions(threshold=sys.maxsize)

In [335]:
np_array_A: np.ndarray = np.arange(24)
np_array_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [336]:
def info(np_array: np.ndarray):
    return " ".join(list(str((k,v)) for (k,v) in {
                "ndim":np_array.ndim,
                "shape":np_array.shape,
                "size":np_array.size,
                "dtype":np_array.dtype.name,
                "itemsize":np_array.itemsize,
                "nbytes":np_array.nbytes,
                "strides":np_array.strides,
                # "base":np_array.base,
                # "imag":np_array.imag,
                # "real":np_array.real
    }.items()))
# print(np_array.T)
# print(np_array.flat)
# print(np_array.ctypes)
# print(np_array.data)
# print(np_array.flags)

In [337]:
info(np_array_A)

"('ndim', 1) ('shape', (24,)) ('size', 24) ('dtype', 'int32') ('itemsize', 4) ('nbytes', 96) ('strides', (4,))"

In [338]:
np_array_A.reshape(2, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [339]:
np_array_A.reshape(12, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [340]:
np_array_dim3 = np_array_A.reshape(2, 3, 4)
np_array_dim3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [341]:
info(np_array_A)

"('ndim', 1) ('shape', (24,)) ('size', 24) ('dtype', 'int32') ('itemsize', 4) ('nbytes', 96) ('strides', (4,))"

In [342]:
info(np.array([1, 2, 3]))

"('ndim', 1) ('shape', (3,)) ('size', 3) ('dtype', 'int32') ('itemsize', 4) ('nbytes', 12) ('strides', (4,))"

In [343]:
info(np.array([1., 2., 3.]))

"('ndim', 1) ('shape', (3,)) ('size', 3) ('dtype', 'float64') ('itemsize', 8) ('nbytes', 24) ('strides', (8,))"

In [344]:
info(np.array([1., 2, 3.]))

"('ndim', 1) ('shape', (3,)) ('size', 3) ('dtype', 'float64') ('itemsize', 8) ('nbytes', 24) ('strides', (8,))"

In [345]:
info(np.array([[1, 2], [3, 4]], dtype=complex))

"('ndim', 2) ('shape', (2, 2)) ('size', 4) ('dtype', 'complex128') ('itemsize', 16) ('nbytes', 64) ('strides', (32, 16))"

In [346]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [347]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [348]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [349]:
np.empty((2, 3))

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8]])

In [350]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [351]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [352]:
np.linspace(0, 2, 10) # 0 to 2 with 10 values

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [353]:
np.linspace(math.pi, math.pi**math.pi, 5)

array([ 3.14159265, 11.47173439, 19.80187613, 28.13201787, 36.46215961])

In [354]:
np_array_B = np.arange(0, 5)
np_array_B

array([0, 1, 2, 3, 4])

In [355]:
np_array_B + 10

array([10, 11, 12, 13, 14])

In [356]:
np_array_B - 10

array([-10,  -9,  -8,  -7,  -6])

In [357]:
np_array_B * 10

array([ 0, 10, 20, 30, 40])

In [358]:
np_array_B / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [359]:
np_array_B + np.arange(-10, -5)

array([-10,  -8,  -6,  -4,  -2])

In [360]:
np_array_B - np.arange(-10, -5)

array([10, 10, 10, 10, 10])

In [361]:
np_array_B * np.arange(-10, -5)

array([  0,  -9, -16, -21, -24])

In [362]:
np_array_B @ np.arange(-10, -5)

-70

In [363]:
np_array_B.sum()

10

In [364]:
np_array_B.min()

0

In [365]:
np_array_B.max()

4

In [366]:
np_array_dim3.sum()

276

In [370]:
np_array_dim3.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [371]:
np_array_dim3.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [372]:
np_array_dim3.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])